
services:
  app:
    container_name: app
    image: 'demo-docker-spring-boot-postgres:1.0.0'
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - app.env
#    environment:
#      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
    depends_on:
      - database


  database:
    image: postgres:latest
    container_name: database
    env_file:
      - database.env
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
